Corrected script to produce the (correct) test results.

diff --git a/Courseworks/201415/Two/ProduceTestResults b/Courseworks/201415/Two/ProduceTestResults
--- a/Courseworks/201415/Two/ProduceTestResults
+++ b/Courseworks/201415/Two/ProduceTestResults
@@ -3,9 +3,9 @@
 
 # Usage:
 
-# ProduceTestResults program testcases_dir testresults_dir
+# ProduceTestResults testcases_dir testresults_dir
 
-# Runs "program" with every file in testcases_dir put as command-line
+# Runs "program=Functions" with every file in testcases_dir put as command-line
 # arguments, placing the results in a file with the same name in
 # directory testresults_dir
 
@@ -14,32 +14,33 @@ set -o nounset
 set -o pipefail
 
 script_name="ProduceTestResults"
-version_number=0.1
+version_number=0.2
 
 errormsg="ERROR[${script_name}]:"
 
-if [[ $# != 3 ]]; then
-  echo "${errormsg} Precisely three arguments are needed:
- program testcases_dir testresults_dir"
+if [[ $# != 2 ]]; then
+  echo "${errormsg} Precisely two arguments are needed:
+ testcases_dir testresults_dir"
   exit 1
 fi
 
-program=$1
-testcases_dir=$2
-testresults_dir=$3
+testcases_dir=$1
+testresults_dir=$2
+program=Functions
 
 for T in ${testcases_dir}/*; do
   B=$(basename $T)
   echo "RUNNING $B"
 set +o errexit
   if [[ -s $T ]]; then
-    java ${program} $(cat $T)
-    returnval=$?
+    cat $T | xargs bash -c 'java '"${program}"' "$@"; echo "$?" > AUSGABE ' -
   else
     java ${program}
-    returnval=$?
+    echo "$?" > AUSGABE
   fi
   cat $T | xargs java ${program} > ${testresults_dir}/$B
 set -o errexit
-  echo ${returnval} > ${testresults_dir}/${B}_RET
+  cat AUSGABE > ${testresults_dir}/${B}_RET
 done
+rm AUSGABE
+
